import os
from decimal import Decimal
from django.core.management.base import BaseCommand
from tracker.models import FoodItem

class Command(BaseCommand):
    help = 'Seeds USDA FoodData Central verified foods into the database'

    def handle(self, *args, **options):
        foods_data = [
            # Poultry & Meat
            {
                'name': 'Chicken Breast (Skinless, Grilled)',
                'category': 'poultry_meat',
                'calories_per_100g': Decimal('165.0'),
                'protein_per_100g': Decimal('31.0'),
                'carbs_per_100g': Decimal('0.0'),
                'fat_per_100g': Decimal('3.6'),
                'fiber_per_100g': Decimal('0.0'),
                'serving_size_g': Decimal('150.0'),
                'serving_unit_name': '1 medium breast (150g)',
                'usda_fdc_id': '171077',
                'is_verified': True,
                'dietary_tags': 'high-protein,gluten-free,keto',
            },
            {
                'name': 'Turkey Breast (Roasted, Skinless)',
                'category': 'poultry_meat',
                'calories_per_100g': Decimal('147.0'),
                'protein_per_100g': Decimal('30.1'),
                'carbs_per_100g': Decimal('0.0'),
                'fat_per_100g': Decimal('1.8'),
                'fiber_per_100g': Decimal('0.0'),
                'serving_size_g': Decimal('140.0'),
                'serving_unit_name': '1 slice/portion (140g)',
                'usda_fdc_id': '171485',
                'is_verified': True,
                'dietary_tags': 'high-protein,lean,gluten-free',
            },
            {
                'name': 'Lean Ground Beef (93/7, Cooked)',
                'category': 'poultry_meat',
                'calories_per_100g': Decimal('172.0'),
                'protein_per_100g': Decimal('26.1'),
                'carbs_per_100g': Decimal('0.0'),
                'fat_per_100g': Decimal('7.5'),
                'fiber_per_100g': Decimal('0.0'),
                'serving_size_g': Decimal('120.0'),
                'serving_unit_name': '1 patty (120g)',
                'usda_fdc_id': '174032',
                'is_verified': True,
                'dietary_tags': 'high-protein,keto',
            },
            {
                'name': 'Pork Tenderloin (Roasted)',
                'category': 'poultry_meat',
                'calories_per_100g': Decimal('143.0'),
                'protein_per_100g': Decimal('26.2'),
                'carbs_per_100g': Decimal('0.0'),
                'fat_per_100g': Decimal('3.5'),
                'fiber_per_100g': Decimal('0.0'),
                'serving_size_g': Decimal('100.0'),
                'serving_unit_name': '1 fillet cut (100g)',
                'usda_fdc_id': '168250',
                'is_verified': True,
                'dietary_tags': 'high-protein,lean',
            },

            # Fish & Seafood
            {
                'name': 'Wild Atlantic Salmon (Cooked)',
                'category': 'fish_seafood',
                'calories_per_100g': Decimal('182.0'),
                'protein_per_100g': Decimal('25.4'),
                'carbs_per_100g': Decimal('0.0'),
                'fat_per_100g': Decimal('8.1'),
                'fiber_per_100g': Decimal('0.0'),
                'serving_size_g': Decimal('150.0'),
                'serving_unit_name': '1 fillet (150g)',
                'usda_fdc_id': '173687',
                'is_verified': True,
                'dietary_tags': 'pescatarian,omega3,high-protein,keto',
            },
            {
                'name': 'Chunk Light Tuna (Canned in Water)',
                'category': 'fish_seafood',
                'calories_per_100g': Decimal('116.0'),
                'protein_per_100g': Decimal('25.5'),
                'carbs_per_100g': Decimal('0.0'),
                'fat_per_100g': Decimal('0.8'),
                'fiber_per_100g': Decimal('0.0'),
                'serving_size_g': Decimal('165.0'),
                'serving_unit_name': '1 can drained (165g)',
                'usda_fdc_id': '171986',
                'is_verified': True,
                'dietary_tags': 'pescatarian,high-protein,lean',
            },
            {
                'name': 'Pacific Cod Fillet (Baked)',
                'category': 'fish_seafood',
                'calories_per_100g': Decimal('105.0'),
                'protein_per_100g': Decimal('23.0'),
                'carbs_per_100g': Decimal('0.0'),
                'fat_per_100g': Decimal('0.9'),
                'fiber_per_100g': Decimal('0.0'),
                'serving_size_g': Decimal('150.0'),
                'serving_unit_name': '1 fillet (150g)',
                'usda_fdc_id': '174227',
                'is_verified': True,
                'dietary_tags': 'pescatarian,high-protein,lean',
            },
            {
                'name': 'Jumbo Shrimp (Steamed/Boiled)',
                'category': 'fish_seafood',
                'calories_per_100g': Decimal('99.0'),
                'protein_per_100g': Decimal('24.0'),
                'carbs_per_100g': Decimal('0.2'),
                'fat_per_100g': Decimal('0.3'),
                'fiber_per_100g': Decimal('0.0'),
                'serving_size_g': Decimal('100.0'),
                'serving_unit_name': '6-8 jumbo shrimp (100g)',
                'usda_fdc_id': '175180',
                'is_verified': True,
                'dietary_tags': 'pescatarian,high-protein,lean,keto',
            },

            # Dairy & Eggs
            {
                'name': 'Whole Large Egg (Hard-boiled / Poached)',
                'category': 'dairy_eggs',
                'calories_per_100g': Decimal('155.0'),
                'protein_per_100g': Decimal('12.6'),
                'carbs_per_100g': Decimal('1.1'),
                'fat_per_100g': Decimal('10.6'),
                'fiber_per_100g': Decimal('0.0'),
                'serving_size_g': Decimal('50.0'),
                'serving_unit_name': '1 large egg (50g)',
                'usda_fdc_id': '173424',
                'is_verified': True,
                'dietary_tags': 'vegetarian,high-protein,keto',
            },
            {
                'name': 'Pure Liquid Egg Whites',
                'category': 'dairy_eggs',
                'calories_per_100g': Decimal('52.0'),
                'protein_per_100g': Decimal('10.9'),
                'carbs_per_100g': Decimal('0.7'),
                'fat_per_100g': Decimal('0.2'),
                'fiber_per_100g': Decimal('0.0'),
                'serving_size_g': Decimal('150.0'),
                'serving_unit_name': '1/2 cup liquid whites (150g)',
                'usda_fdc_id': '172184',
                'is_verified': True,
                'dietary_tags': 'vegetarian,high-protein,lean',
            },
            {
                'name': 'Nonfat Plain Greek Yogurt (0% Fat)',
                'category': 'dairy_eggs',
                'calories_per_100g': Decimal('59.0'),
                'protein_per_100g': Decimal('10.3'),
                'carbs_per_100g': Decimal('3.6'),
                'fat_per_100g': Decimal('0.4'),
                'fiber_per_100g': Decimal('0.0'),
                'serving_size_g': Decimal('170.0'),
                'serving_unit_name': '1 single-serve tub (170g)',
                'usda_fdc_id': '170903',
                'is_verified': True,
                'dietary_tags': 'vegetarian,high-protein,probiotic',
            },
            {
                'name': 'Low-Fat Cottage Cheese (2% Milkfat)',
                'category': 'dairy_eggs',
                'calories_per_100g': Decimal('81.0'),
                'protein_per_100g': Decimal('11.0'),
                'carbs_per_100g': Decimal('4.3'),
                'fat_per_100g': Decimal('2.3'),
                'fiber_per_100g': Decimal('0.0'),
                'serving_size_g': Decimal('150.0'),
                'serving_unit_name': '1 cup portion (150g)',
                'usda_fdc_id': '173418',
                'is_verified': True,
                'dietary_tags': 'vegetarian,high-protein,casein',
            },
            {
                'name': 'Parmesan Cheese (Aged, Grated)',
                'category': 'dairy_eggs',
                'calories_per_100g': Decimal('392.0'),
                'protein_per_100g': Decimal('35.8'),
                'carbs_per_100g': Decimal('3.2'),
                'fat_per_100g': Decimal('25.8'),
                'fiber_per_100g': Decimal('0.0'),
                'serving_size_g': Decimal('25.0'),
                'serving_unit_name': '2 tbsp grated (25g)',
                'usda_fdc_id': '170853',
                'is_verified': True,
                'dietary_tags': 'vegetarian,high-protein,keto',
            },

            # Legumes & Beans
            {
                'name': 'Cooked Brown Lentils',
                'category': 'legumes_beans',
                'calories_per_100g': Decimal('116.0'),
                'protein_per_100g': Decimal('9.0'),
                'carbs_per_100g': Decimal('20.1'),
                'fat_per_100g': Decimal('0.4'),
                'fiber_per_100g': Decimal('7.9'),
                'serving_size_g': Decimal('198.0'),
                'serving_unit_name': '1 cup cooked (198g)',
                'usda_fdc_id': '172421',
                'is_verified': True,
                'dietary_tags': 'vegan,vegetarian,high-fiber,plant-based',
            },
            {
                'name': 'Cooked Chickpeas (Garbanzo Beans)',
                'category': 'legumes_beans',
                'calories_per_100g': Decimal('164.0'),
                'protein_per_100g': Decimal('8.9'),
                'carbs_per_100g': Decimal('27.4'),
                'fat_per_100g': Decimal('2.6'),
                'fiber_per_100g': Decimal('7.6'),
                'serving_size_g': Decimal('164.0'),
                'serving_unit_name': '1 cup cooked (164g)',
                'usda_fdc_id': '173757',
                'is_verified': True,
                'dietary_tags': 'vegan,vegetarian,high-fiber,plant-based',
            },
            {
                'name': 'Cooked Black Beans',
                'category': 'legumes_beans',
                'calories_per_100g': Decimal('132.0'),
                'protein_per_100g': Decimal('8.9'),
                'carbs_per_100g': Decimal('23.7'),
                'fat_per_100g': Decimal('0.5'),
                'fiber_per_100g': Decimal('8.7'),
                'serving_size_g': Decimal('172.0'),
                'serving_unit_name': '1 cup cooked (172g)',
                'usda_fdc_id': '173735',
                'is_verified': True,
                'dietary_tags': 'vegan,vegetarian,high-fiber,plant-based',
            },
            {
                'name': 'Edamame (Green Soybeans, Steamed)',
                'category': 'legumes_beans',
                'calories_per_100g': Decimal('122.0'),
                'protein_per_100g': Decimal('11.9'),
                'carbs_per_100g': Decimal('8.9'),
                'fat_per_100g': Decimal('5.2'),
                'fiber_per_100g': Decimal('5.2'),
                'serving_size_g': Decimal('155.0'),
                'serving_unit_name': '1 cup shelled (155g)',
                'usda_fdc_id': '172442',
                'is_verified': True,
                'dietary_tags': 'vegan,vegetarian,complete-protein',
            },

            # Plant Proteins & Meat Alternatives
            {
                'name': 'Firm Tofu (Organic Soy)',
                'category': 'plant_protein',
                'calories_per_100g': Decimal('144.0'),
                'protein_per_100g': Decimal('15.8'),
                'carbs_per_100g': Decimal('2.8'),
                'fat_per_100g': Decimal('8.7'),
                'fiber_per_100g': Decimal('2.3'),
                'serving_size_g': Decimal('125.0'),
                'serving_unit_name': '1/2 block (125g)',
                'usda_fdc_id': '172448',
                'is_verified': True,
                'dietary_tags': 'vegan,vegetarian,gluten-free,high-protein',
            },
            {
                'name': 'Tempeh (Fermented Whole Soy)',
                'category': 'plant_protein',
                'calories_per_100g': Decimal('192.0'),
                'protein_per_100g': Decimal('20.3'),
                'carbs_per_100g': Decimal('7.6'),
                'fat_per_100g': Decimal('10.8'),
                'fiber_per_100g': Decimal('4.8'),
                'serving_size_g': Decimal('100.0'),
                'serving_unit_name': '1 serving (100g)',
                'usda_fdc_id': '172459',
                'is_verified': True,
                'dietary_tags': 'vegan,vegetarian,high-protein,probiotic',
            },
            {
                'name': 'Seitan (Vital Wheat Gluten)',
                'category': 'plant_protein',
                'calories_per_100g': Decimal('370.0'),
                'protein_per_100g': Decimal('75.2'),
                'carbs_per_100g': Decimal('13.8'),
                'fat_per_100g': Decimal('1.9'),
                'fiber_per_100g': Decimal('1.5'),
                'serving_size_g': Decimal('85.0'),
                'serving_unit_name': '1 piece (85g)',
                'usda_fdc_id': '174276',
                'is_verified': True,
                'dietary_tags': 'vegan,vegetarian,ultra-high-protein',
            },

            # Nuts & Seeds
            {
                'name': 'Natural Peanut Butter (100% Peanuts)',
                'category': 'nuts_seeds',
                'calories_per_100g': Decimal('588.0'),
                'protein_per_100g': Decimal('25.1'),
                'carbs_per_100g': Decimal('20.0'),
                'fat_per_100g': Decimal('50.4'),
                'fiber_per_100g': Decimal('6.0'),
                'serving_size_g': Decimal('32.0'),
                'serving_unit_name': '2 tbsp (32g)',
                'usda_fdc_id': '174268',
                'is_verified': True,
                'dietary_tags': 'vegan,vegetarian,healthy-fats',
            },
            {
                'name': 'Whole Raw Almonds',
                'category': 'nuts_seeds',
                'calories_per_100g': Decimal('579.0'),
                'protein_per_100g': Decimal('21.2'),
                'carbs_per_100g': Decimal('21.6'),
                'fat_per_100g': Decimal('49.9'),
                'fiber_per_100g': Decimal('12.5'),
                'serving_size_g': Decimal('28.0'),
                'serving_unit_name': '1 handful / 23 almonds (28g)',
                'usda_fdc_id': '170567',
                'is_verified': True,
                'dietary_tags': 'vegan,vegetarian,high-fiber,vitamin-e',
            },
            {
                'name': 'Shelled Hemp Hearts (Raw Seeds)',
                'category': 'nuts_seeds',
                'calories_per_100g': Decimal('553.0'),
                'protein_per_100g': Decimal('31.6'),
                'carbs_per_100g': Decimal('8.7'),
                'fat_per_100g': Decimal('48.8'),
                'fiber_per_100g': Decimal('4.0'),
                'serving_size_g': Decimal('30.0'),
                'serving_unit_name': '3 tbsp (30g)',
                'usda_fdc_id': '170148',
                'is_verified': True,
                'dietary_tags': 'vegan,vegetarian,omega3,complete-protein',
            },
            {
                'name': 'Organic Chia Seeds',
                'category': 'nuts_seeds',
                'calories_per_100g': Decimal('486.0'),
                'protein_per_100g': Decimal('16.5'),
                'carbs_per_100g': Decimal('42.1'),
                'fat_per_100g': Decimal('30.7'),
                'fiber_per_100g': Decimal('34.4'),
                'serving_size_g': Decimal('25.0'),
                'serving_unit_name': '2 tbsp (25g)',
                'usda_fdc_id': '170554',
                'is_verified': True,
                'dietary_tags': 'vegan,vegetarian,ultra-high-fiber,omega3',
            },

            # Grains & Cereals
            {
                'name': 'Rolled Oats (Whole Grain, Dry)',
                'category': 'grains_cereals',
                'calories_per_100g': Decimal('379.0'),
                'protein_per_100g': Decimal('13.2'),
                'carbs_per_100g': Decimal('67.7'),
                'fat_per_100g': Decimal('6.5'),
                'fiber_per_100g': Decimal('10.1'),
                'serving_size_g': Decimal('50.0'),
                'serving_unit_name': '1/2 cup dry (50g)',
                'usda_fdc_id': '173904',
                'is_verified': True,
                'dietary_tags': 'vegan,vegetarian,wholegrain,beta-glucan',
            },
            {
                'name': 'Cooked Quinoa (Complete Grain)',
                'category': 'grains_cereals',
                'calories_per_100g': Decimal('120.0'),
                'protein_per_100g': Decimal('4.4'),
                'carbs_per_100g': Decimal('21.3'),
                'fat_per_100g': Decimal('1.9'),
                'fiber_per_100g': Decimal('2.8'),
                'serving_size_g': Decimal('185.0'),
                'serving_unit_name': '1 cup cooked (185g)',
                'usda_fdc_id': '168917',
                'is_verified': True,
                'dietary_tags': 'vegan,vegetarian,gluten-free,complete-protein',
            },
            {
                'name': 'Whole Grain Brown Rice (Cooked)',
                'category': 'grains_cereals',
                'calories_per_100g': Decimal('123.0'),
                'protein_per_100g': Decimal('2.7'),
                'carbs_per_100g': Decimal('25.6'),
                'fat_per_100g': Decimal('0.9'),
                'fiber_per_100g': Decimal('1.6'),
                'serving_size_g': Decimal('195.0'),
                'serving_unit_name': '1 cup cooked (195g)',
                'usda_fdc_id': '169704',
                'is_verified': True,
                'dietary_tags': 'vegan,vegetarian,gluten-free,wholegrain',
            },

            # Vegetables & Greens
            {
                'name': 'Broccoli Florets (Steamed)',
                'category': 'vegetables_fruits',
                'calories_per_100g': Decimal('35.0'),
                'protein_per_100g': Decimal('2.8'),
                'carbs_per_100g': Decimal('7.2'),
                'fat_per_100g': Decimal('0.4'),
                'fiber_per_100g': Decimal('2.6'),
                'serving_size_g': Decimal('150.0'),
                'serving_unit_name': '1 cup florets (150g)',
                'usda_fdc_id': '170379',
                'is_verified': True,
                'dietary_tags': 'vegan,vegetarian,antioxidant,low-calorie',
            },
            {
                'name': 'Fresh Baby Spinach (Raw)',
                'category': 'vegetables_fruits',
                'calories_per_100g': Decimal('23.0'),
                'protein_per_100g': Decimal('2.9'),
                'carbs_per_100g': Decimal('3.6'),
                'fat_per_100g': Decimal('0.4'),
                'fiber_per_100g': Decimal('2.2'),
                'serving_size_g': Decimal('85.0'),
                'serving_unit_name': '3 cups raw (85g)',
                'usda_fdc_id': '170417',
                'is_verified': True,
                'dietary_tags': 'vegan,vegetarian,iron,nutrient-dense',
            },

            # Protein Powders & Supplements
            {
                'name': 'Whey Protein Isolate (100% Pure)',
                'category': 'supplements',
                'calories_per_100g': Decimal('370.0'),
                'protein_per_100g': Decimal('88.0'),
                'carbs_per_100g': Decimal('2.0'),
                'fat_per_100g': Decimal('1.0'),
                'fiber_per_100g': Decimal('0.0'),
                'serving_size_g': Decimal('30.0'),
                'serving_unit_name': '1 scoop (30g)',
                'usda_fdc_id': '173177',
                'is_verified': True,
                'dietary_tags': 'vegetarian,ultra-high-protein,bcaa',
            },
            {
                'name': 'Organic Pea Protein Isolate (Plant-Based)',
                'category': 'supplements',
                'calories_per_100g': Decimal('395.0'),
                'protein_per_100g': Decimal('80.0'),
                'carbs_per_100g': Decimal('5.0'),
                'fat_per_100g': Decimal('6.0'),
                'fiber_per_100g': Decimal('4.0'),
                'serving_size_g': Decimal('30.0'),
                'serving_unit_name': '1 scoop (30g)',
                'usda_fdc_id': '173180',
                'is_verified': True,
                'dietary_tags': 'vegan,vegetarian,hypoallergenic,high-protein',
            },
            {
                'name': 'Micellar Casein Protein Powder',
                'category': 'supplements',
                'calories_per_100g': Decimal('360.0'),
                'protein_per_100g': Decimal('78.0'),
                'carbs_per_100g': Decimal('4.0'),
                'fat_per_100g': Decimal('1.5'),
                'fiber_per_100g': Decimal('0.0'),
                'serving_size_g': Decimal('32.0'),
                'serving_unit_name': '1 scoop (32g)',
                'usda_fdc_id': '173185',
                'is_verified': True,
                'dietary_tags': 'vegetarian,slow-digesting,nighttime-recovery',
            }
        ]

        created_count = 0
        updated_count = 0
        for item in foods_data:
            obj, created = FoodItem.objects.update_or_create(
                name=item['name'],
                defaults=item
            )
            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(self.style.SUCCESS(
            f"Successfully seeded USDA database: {created_count} created, {updated_count} updated."
        ))
