# Generated by Django 4.2.30 on 2026-09-29 08:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('poultry_meat', 'Poultry & Meat'), ('fish_seafood', 'Fish & Seafood'), ('dairy_eggs', 'Dairy & Eggs'), ('legumes_beans', 'Legumes, Beans & Lentils'), ('plant_protein', 'Tofu & Plant Proteins'), ('nuts_seeds', 'Nuts & Seeds'), ('grains_cereals', 'Grains & Cereals'), ('vegetables_fruits', 'Vegetables & Fruits'), ('supplements', 'Protein Powders & Supplements'), ('prepared_dishes', 'Prepared Dishes')], max_length=50)),
                ('calories_per_100g', models.DecimalField(decimal_places=1, max_digits=6)),
                ('protein_per_100g', models.DecimalField(decimal_places=1, max_digits=5)),
                ('carbs_per_100g', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fat_per_100g', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fiber_per_100g', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('serving_size_g', models.DecimalField(decimal_places=1, default=100.0, max_digits=6)),
                ('serving_unit_name', models.CharField(default='100g (standard serving)', max_length=60)),
                ('usda_fdc_id', models.CharField(blank=True, help_text='USDA FoodData Central Identifier', max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=True, help_text='Verified USDA FoodData item')),
                ('dietary_tags', models.CharField(blank=True, help_text='Comma-separated tags e.g. vegan,vegetarian,high-protein', max_length=120)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=26)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('weight_kg', models.DecimalField(decimal_places=1, default=70.0, max_digits=5)),
                ('height_cm', models.DecimalField(decimal_places=1, default=175.0, max_digits=5)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (Little or no exercise)'), ('light', 'Lightly Active (1-3 days/week)'), ('moderate', 'Moderately Active (3-5 days/week)'), ('very_active', 'Very Active (6-7 days/week)'), ('extra_active', 'Extra Active (Heavy training / physical labor)')], default='moderate', max_length=20)),
                ('fitness_goal', models.CharField(choices=[('maintenance', 'Maintain Weight & Vitality'), ('muscle_gain', 'Build Muscle / Hypertrophy'), ('fat_loss', 'Fat Loss / Cutting (Preserve Lean Mass)'), ('endurance', 'Athletic Endurance & Performance')], default='muscle_gain', max_length=20)),
                ('dietary_preference', models.CharField(choices=[('omnivore', 'Omnivore (All foods)'), ('vegetarian', 'Vegetarian (No meat/fish)'), ('vegan', 'Vegan (Strict plant-based)'), ('pescatarian', 'Pescatarian (Fish & plant-based)'), ('keto', 'Keto / Low-Carb')], default='omnivore', max_length=20)),
                ('target_calories', models.PositiveIntegerField(default=2300)),
                ('target_protein_g', models.DecimalField(decimal_places=1, default=140.0, max_digits=6)),
                ('target_carbs_g', models.DecimalField(decimal_places=1, default=260.0, max_digits=6)),
                ('target_fat_g', models.DecimalField(decimal_places=1, default=65.0, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=150)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack / Post-Workout')], max_length=20)),
                ('serving_amount_g', models.DecimalField(decimal_places=1, default=100.0, max_digits=6)),
                ('calories', models.DecimalField(decimal_places=1, max_digits=6)),
                ('protein_g', models.DecimalField(decimal_places=1, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=1, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=1, max_digits=6)),
                ('logged_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_logs', to='tracker.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
